on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        # TODO(mvdan): fix and enable windows
        # TODO(mvdan): mac seems to timeout too often
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
    - name: Checkout codec-fixtures
      uses: actions/checkout@v2
      with:
        repository: ipld/codec-fixtures
        path: codec-fixtures
    - name: Run codec-fixtures tests
      run: |
        cd codec-fixtures/go
        echo "replace github.com/ipld/go-ipld-prime => ../../" >> go.mod
        go test -v ./...

